### ISSUE TITLE
`gomodctl check` throws panic

### ISSUE THREAD

**Issue by Dentrax** [beatlabs/gomodctl#21]
**Describe the bug**
Command throws paninc

**To Reproduce**
1. Go to project
2. Type `gomodctl check`
3. See error

**Actual behavior**
```
Config File "gomodctl" Not Found in "[/Users/furkan]"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x11fa4ae]

goroutine 1 [running]:
github.com/Masterminds/semver.(*Version).Original(...)
	/home/runner/go/pkg/mod/github.com/!masterminds/semver@v1.5.0/version.go:126
github.com/beatlabs/gomodctl/internal/cmd/check.(*Options).Execute(0xc0001561d0, 0x1628660, 0xc000156170)
	/home/runner/work/gomodctl/gomodctl/internal/cmd/check/check.go:62 +0x14e
github.com/beatlabs/gomodctl/internal/cmd/check.NewCmdCheck.func2(0xc000174500, 0x1995a50, 0x0, 0x0)
	/home/runner/work/gomodctl/gomodctl/internal/cmd/check/check.go:41 +0x3c
github.com/spf13/cobra.(*Command).execute(0xc000174500, 0x1995a50, 0x0, 0x0, 0xc000174500, 0x1995a50)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x19705c0, 0xc0000c5f08, 0x1, 0x1)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.Execute()
	/home/runner/work/gomodctl/gomodctl/cmd/gomodctl/gomodctl.go:80 +0x476
main.main()
	/home/runner/work/gomodctl/gomodctl/cmd/gomodctl/gomodctl.go:124 +0x20
```

**Desktop (please complete the following information):**
 - OS: `macOS`

**Comment by ormanli** [comment]
Hi,

Thanks for reporting. Can you also add the `go.mod` file which you are trying to check for the update?

**Comment by KenanBek** [comment]
@Dentrax also could you please specify how did you install it? With `brew` or `go get`. And in case of the second option, what is your local Go version?

**Comment by Dentrax** [comment]
Sorry, i forgot the add that informations. :)

I just installed it from `brew`
Go ver.: `go version go1.13.6 darwin/amd64`

Important info: There may be _X_ more private repositories that it shouldn't be count or access for.

```
module test-project

go 1.13

require (
	github.com/afex/hystrix-go v0.0.0-20180502004556-fa1af6a1f4f5
	github.com/cespare/xxhash/v2 v2.1.1 // indirect
	github.com/fsnotify/fsnotify v1.4.7
	github.com/gin-gonic/gin v1.5.0 // indirect
	github.com/go-openapi/jsonreference v0.19.3 // indirect
	github.com/go-openapi/spec v0.19.4 // indirect
	github.com/go-playground/universal-translator v0.17.0 // indirect
	github.com/json-iterator/go v1.1.8 // indirect
	github.com/klauspost/compress v1.9.3 // indirect
	github.com/konsorten/go-windows-terminal-sequences v1.0.2 // indirect
	github.com/labstack/echo/v4 v4.1.11
	github.com/leodido/go-urn v1.2.0 // indirect
	github.com/mailru/easyjson v0.7.0 // indirect
	github.com/mattn/go-colorable v0.1.4 // indirect
	github.com/mattn/go-isatty v0.0.10 // indirect
	github.com/newrelic/go-agent v2.16.0+incompatible // indirect
	github.com/prometheus/client_golang v1.2.1 // indirect
	github.com/prometheus/procfs v0.0.8 // indirect
	github.com/sirupsen/logrus v1.4.2
	github.com/spf13/viper v1.4.0
	github.com/stretchr/testify v1.4.0
	github.com/swaggo/echo-swagger v0.0.0-20190329130007-1219b460a043
	github.com/swaggo/swag v1.6.3 // indirect
	github.com/valyala/fasthttp v1.6.0 // indirect
	github.com/valyala/fasttemplate v1.1.0 // indirect
	golang.org/x/crypto v0.0.0-20191128160524-b544559bb6d1 // indirect
	golang.org/x/net v0.0.0-20191126235420-ef20fe5d7933
	golang.org/x/sys v0.0.0-20191128015809-6d18c012aee9 // indirect
	golang.org/x/tools v0.0.0-20191130070609-6e064ea0cf2d // indirect
	gopkg.in/check.v1 v1.0.0-20190902080502-41f04d3bba15 // indirect
	gopkg.in/go-playground/validator.v9 v9.30.2 // indirect
	gopkg.in/yaml.v2 v2.2.7 // indirect
	custom.private.com/xxx/project v1.0.0 // indirect
	custom.private.com/xxx/project/v2 v2.0.0
)
```

**Comment by ormanli** [comment]
I tried to reproduce this problem with a test case, replacing the last 2 required with the private module I created now. 

I got `verifying github.com/ormanli/go-plus@v0.0.1/go.mod: github.com/ormanli/go-plus@v0.0.1/go.mod: reading https://sum.golang.org/lookup/github.com/ormanli/go-plus@v0.0.1: 410 Gone`. 

After this, I came across this [issue](https://github.com/golang/go/issues/31818), which describes the same. Since we are using `go mod` underneath to fetch updates, we don't have much to do now.

**Comment by Dentrax** [comment]
You can just ignore custom private modules, actually, which is fine for now, instead of throw panic.

**Comment by Dentrax** [comment]
@ormanli Even though i upgraded to ver. _0.1.1_ with _homebrew_ , still getting exactly same segmentation violation on same project and environment. :(

**Comment by ormanli** [comment]
I updated to v0.1.2 which solves panic. For private modules, I added a section to readme. Can you check if panic is solved?

**Comment by Dentrax** [comment]
Panic is solved but now getting another weird error: `cannot register licenses from archive: open /home/runner/go/pkg/mod/github.com/google/licenseclassifier@v0.0.0-20200108231022-9dfa8d8474eb/licenses/licenses.db: no such file or directory`

**Comment by ormanli** [comment]
It looks like build process is broken, I will try to fix as soon as possible.

**Comment by ormanli** [comment]
Hi, can you try latest version 0.2.1 ?

**Comment by Dentrax** [comment]
Looks like now fixed. :)

But i think you should improve the output log:

```
  github.com/afex/hystrix-go           | v0.0.0-20180502004556-fa1af6a1f4f5 | failed because of: no version
                                       |                                    | available
```

`failed because of: no version available` error occupies 2 lines, should be 1 think. Also colored output for updates should be fine :)
